name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker image
        run: |
          TAG=latest
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            TAG=dev
          fi
          docker build -t blooossom/shortping:$TAG .

      - name: Push Backend Docker image
        run: |
          TAG=latest
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            TAG=dev
          fi
          docker push blooossom/shortping:$TAG

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker image
        run: |
          cd shortping-front
          TAG=latest
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            TAG=dev
          fi
          docker build . -t blooossom/shortping-front:$TAG

      - name: Push Frontend Docker image
        run: |
          TAG=latest
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            TAG=dev
          fi
          docker push blooossom/shortping-front:$TAG
